export const GET_GENDER_OPTIONS = "GET_GENDER_OPTIONS"
export const GET_SYMPTOMS_OPTIONS = "GET_SYMPTOMS_OPTIONS"
export const GET_SYMPTOMS_OPTIONS_FAILED = "GET_SYMPTOMS_OPTIONS_FAILED"
export const SET_DIAGNOSIS_DATA = "SET_DIAGNOSIS_DATA"